# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mergeCountWins <- function(group1, group2) {
    .Call(`_boosttest_mergeCountWins`, group1, group2)
}

rcppeigen_hello_world <- function() {
    .Call(`_boosttest_rcppeigen_hello_world`)
}

rcppeigen_outerproduct <- function(x) {
    .Call(`_boosttest_rcppeigen_outerproduct`, x)
}

rcppeigen_innerproduct <- function(x) {
    .Call(`_boosttest_rcppeigen_innerproduct`, x)
}

rcppeigen_bothproducts <- function(x) {
    .Call(`_boosttest_rcppeigen_bothproducts`, x)
}

